name: Deploy to GitHub Pages

on:
  push:
    branches:
      - update-urls

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CORS_ACCESS_TOKEN }}
        publish_dir: ./dist

    - name: Add CORS headers
      run: |
        echo "/*" >> dist/_headers
        echo "  Access-Control-Allow-Origin: *" >> dist/_headers
        echo "  Content-Type: application/json" >> dist/_headers
